config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  authenticated :user do
    root 'registered_apps#index', as: :authenticated_root
  end

  namespace :api, defaults: { format: :json } do
    match '/events', to: 'events#preflight', via: [:options]
    resources :events, only: [:create]
  end

  resources :contacts, only: [:new, :create]

  resources :registered_apps
  get 'welcome/landing'
  get 'welcome/info'

  root to: 'welcome#landing'

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  attribute :nickname,  :captcha  => true

  def headers
    {
    :subject => "Mail from tedmetrics",
    :to => "tedmlopez@gmail.com",
    :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :registered_app
end

app/models/registered_app.rb
class RegisteredApp < ActiveRecord::Base
  belongs_to :user
  has_many :events
  validates :name, :presence => true, :uniqueness => true
  validates :url, :presence => true
end

app/models/registered_application.rb
class RegisteredApplication < ActiveRecord::Base
  belongs_to :user
  has_many :events
  validates :name, :presence => true, :uniqueness => true
  validates :url, :presence => true
end

app/models/registration.rb
class Registration < ActiveRecord::Base
  belongs_to :user
  has_many :events
  validates :name, :presence => true, :uniqueness => true
  validates :url, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable #, :confirmable

  has_many :registered_apps, dependent: :destroy

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
        where(conditions.to_hash).first
    end
  end

end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
  before_filter :set_access_control_headers
  skip_before_action :verify_authenticity_token

  def create
    registered_app = RegisteredApp.find_by(url: request.env['HTTP_ORIGIN']+'/')

    if registered_app.nil?
      render json: "Unregistered application", status: :unprocessable_entity
      else
        @event = registered_app.events.build(event_params)
          if @event.save
            render json: @event, status: :created
          else
            render json: { error: "Missing event name" }, status: :unprocessable_entity
          end
    end

  end

  def preflight
    head 200
  end

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Content-Type'
  end

  private

  def event_params
    params.require(:event).permit(:name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
  before_action :authenticate_user!, except: [:about]

  def index
    @registered_applications = current_user.registered_applications
  end

  def new
    @user = current_user
    @registered_application = RegisteredApplication.new
  end

  def show
    @registered_application = current_user.registered_applications.find(params[:id])
    @events = @registered_application.events(:group => 'name')
  end

  def create
    @registered_application = current_user.registered_applications.build(registration_params)

      if @registered_application.save
        flash[:notice] = "App has been added."
        redirect_to root_path
      else
        flash.now[:alert] = "There was an error adding the app. Please try again."
        render :new
      end
  end

  def destroy
    @user = current_user
    @registered_application = RegisteredApplication.find(params[:id])

      if @registered_application.destroy
        flash[:success] = "App has been removed."
      else
        flash[:error] = "App could not be removed."
      end
      redirect_to root_path
  end

  def about

  end

  private

    def registration_params
      params.require(:registered_application).permit(:name, :url, :user_id)
    end


end

app/controllers/registered_apps_controller.rb
class RegisteredAppsController < ApplicationController
  before_action :authenticate_user!, except: [:info]

  def landing
  end

  def info
  end

  def index
    @registered_apps = current_user.registered_apps
  end

  def show
    @registered_app = current_user.registered_apps.find(params[:id])
    @events = @registered_app.events(:group => 'name')
  end

  def new
    @user = current_user
    @registered_app = RegisteredApp.new
  end

  def create
    @registered_app = current_user.registered_apps.build(registered_app_params)

      if @registered_app.save
        flash[:notice] = "App has been added."
        redirect_to @registered_app
      else
        flash.now[:alert] = "There was an error adding the app. Please try again."
        render :new
      end
  end

  def destroy
    @user = current_user
    @registered_app = RegisteredApp.find(params[:id])

      if @registered_app.destroy
        flash[:success] = "App has been removed."
      else
        flash[:error] = "App could not be removed."
      end
      redirect_to registered_apps_path action: "index"
  end

  private

  def registered_app_params
    params.require(:registered_app).permit(:name, :url, :user_id)
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def landing
  end

  def info
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/create.html.erb
<div class="center contact">
  <h3 id="page_title">Thanks for your message.</h3>
  <h5>We'll get back to you soon.</h5>
</div>

app/views/contacts/new.html.erb
<h3 class="headers">Contact Us</h3>

<div>
  <%= form_for @contact do |f| %>
  <label for="contact_name"><i class="material-icons prefix">account_circle</i></label><br>
  <input required="required" type="text" name="contact[name]" id="contact_name" placeholder="Name" />

  <br>

  <label for="contact_email"><i class="material-icons prefix">email</i></label><br>
  <input required="required" type="email" name="contact[email]" id="contact_email" placeholder="Email" />

  <br>

  <label for="contact_message"><i class="material-icons prefix">comment</i></label><br>
  <textarea as="text" name="contact[message]" id="contact_message" placeholder="Message">
</textarea>

  <div style="display:none">
    <label for="contact_nickname">Nickname</label><br>
    <input hint="leave this field blank" type="text" name="contact[nickname]" id="contact_nickname" />
  </div>

  <input type="submit" name="commit" value="Send Message" class="waves-effect waves-light btn" />
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>tedmetrics</title>
  <meta name="viewport" content="width=device-width, initial-scale = 1.0, maximum-scale=1.0, user-scalable=no" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav>
    <div class="nav-wrapper">
      <%= link_to "tedmetrics", root_path, class: "logo" %>
      <ul class="right">
        <% if user_signed_in? %>
            <li><%= link_to destroy_user_session_path, method: :delete do %>
                <i class="material-icons left link-item login-link">person</i>
                <% end %>
            </li>
        <% end %>
        <li><%= link_to root_path do %>
            <i class="material-icons left link-item">view_headline</i>
            <% end %>
        </li>
        <li><%= link_to new_contact_path do %>
            <i class="material-icons left link-item">mail_outline</i>
            <% end %>
        </li>
        <li><%= link_to welcome_info_path do %>
            <i class="material-icons left link-item">details</i>
            <% end %>
        </li>
      </ul>
    </div>
  </nav>

  <% if notice %>
    <div id="notice-wrapper">
      <p class="notice"><%= notice %></p>
    </div>
  <% elsif alert %>
    <div id="notice-wrapper">
      <p class="alert"><%= alert %></p>
    </div>
  <%end %>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/registered_applications/about.html.erb
  <div id="app_title">
    <h1>Welcome to blocmetrics</h1>
    <p>An analytics tool for you. Create an account to track activity on your applications: </p>
    <ul>
      <li><%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %></li><br>
      <li><%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %></li>
    </ul>
  </div>

app/views/registered_applications/index.html.erb
  <%= link_to "Register an app", new_registered_application_path%>

  <% if current_user.registered_applications.any? %>
    <h1>Your registered apps:</h1>

  <table>
    <thead>
      <tr>
        <th>App</th>
        <th>App URL</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @registered_applications.each do |app| %>
        <tr>
          <td><%= link_to app.name, registered_application_path(app) %></td>
          <td><%= app.url %></td>

          <% if current_user == app.user %>
            <td><%= link_to 'Remove', registered_application_path(app), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>

<% else %>
  <h1>You have not registered any apps</h1>
<%end %>

app/views/registered_applications/new.html.erb
<h2>Register a new app:</h2>

<%= form_for @registered_application do |f| %>
  <%= f.label :name %>:<br />
  <%= f.text_field :name, placeholder: "Enter application name" %><br />

  <%= f.label :url %>:<br />
  <%= f.text_field :url, placeholder: "Enter application URL" %><br />
  <br>
  <%= f.submit %>
<% end %>
<br>

app/views/registered_applications/show.html.erb
<h1> Show Page </h1>

<div class="row">
  	<div class="col-md-8">
  		<h4>URL: <%= link_to @registered_application.url, "http://#{@registered_application.url}" %></h4>
  		<p>Added by <%= @registered_application.user.email %></p>

 		<% @events.group_by(&:name).each do |name, events| %>
 			 <%= name %> | <%= events.count %>
 		<% end %>

 		<%= pie_chart @registered_application.events.group(:name).count %>
    <%= line_chart @registered_application.events.group_by_day(:created_at).count %>
 		<p>Added by <%= @registered_application.user.email %></p>
  	</div>
</div>

app/views/registered_apps/about.html.erb
<div id="app_title">
  <h1 class="headers">Welcome to tedmetrics</h1>
  <h5 class="center">An analytics tool for you. Create an account to track activity on your applications: </h5>
  <div class="center home-btns">
    <%= link_to "Sign Up", new_user_registration_path, :class => 'waves-effect waves-light btn'  %>
    <%= link_to "Sign In", new_user_session_path, :class => 'waves-effect waves-light btn'  %>
  </div>
</div>

app/views/registered_apps/index.html.erb
<% if current_user.registered_apps.any? %>
  <div class="headers">
    <h3>Your registered apps:</h3>
    <br>
    <%= link_to "Register a new app", new_registered_app_path, :class => 'waves-effect waves-light btn' %>
  </div>

<table class="highlight centered">
  <thead>
    <tr>
      <th>App</th>
      <th>App URL</th>
      <th colspan="3">Remove</th>
    </tr>
  </thead>

  <tbody>
    <% @registered_apps.each do |app| %>
      <tr>
        <td><%= link_to app.name, registered_app_path(app) %></td>
        <td><%= app.url %></td>

        <% if current_user == app.user %>
          <td>
            <%= link_to registered_app_path(app), method: :delete, data: { confirm: 'Are you sure?' } do %>
              <i class="material-icons">delete</i>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<% else %>
<div class="headers">
  <h3>You have not registered any apps</h3>
  <%= link_to "Register a new app", new_registered_app_path, :class => 'waves-effect waves-light btn' %>
</div>
<%end %>

app/views/registered_apps/new.html.erb
<h3 class="headers">Register a new app:</h3>

<%= form_for [@registered_app] do |f| %>
  <input type="text" name="registered_app[name]" id="registered_app_name" placeholder="Name" /><br />

  <input type="text" name="registered_app[url]" id="registered_app_url" placeholder="URL" /><br />

  <input type="submit" name="commit" value="Create Registered app" class="waves-effect waves-light btn" />
<% end %>
<br>
<div class="devise-links">
  <%= link_to 'Back', root_path %>
</div>

app/views/registered_apps/show.html.erb
<h2> <%= @registered_app.name %> </h2>
<h5>URL: <%= link_to @registered_app.url, "#{@registered_app.url}", target: "_blank" %></h5>
<p>Added by <%= @registered_app.user.username %></p>

<div class="row app-stats">
	<div class="col-md-8">
		<h5><%= @events.count %> total events exist for this app</h5>
		<ul><% @events.group_by(&:name).each do |name, events| %></ul>
 			 <li><%= name %> : <%= events.count %></li>
 		<% end %>

		<div class="pie">
			<%= pie_chart @registered_app.events.group(:name).count %>
		</div>
		<div class="line">
    	<%= line_chart @registered_app.events.group_by_day(:created_at, range: 30.days.ago..Time.now).count %>
			<h5>Events By Day</h5>
		</div>
	</div>
</div>

app/views/welcome/info.html.erb
<h3 class="headers">Thanks for using tedmetrics</h3>
<h3>Getting started </h3>
<br>
<h5>Using tedmetrics in your project is easy and only requires two steps:</h5>
<br>
<h5>1: Insert the following JavaScript code snippet into your project to track the events:</h5>

<code>var tedmetrics = {};

tedmetrics.report = function(eventName){

  /* Create an event JSON object to send to the tedmetrics analytics service. */
  var event = {event: { name: eventName }};

  /* Initialize a new XMLHttpRequest() (AJAX request) */
  var request = new XMLHttpRequest();

  /* Set the HTTP method to POST, the url of our events endpoint, and allow the request to run asynchronously. */
  request.open("POST", "https://tedmetrics.herokuapp.com/api/events", true);

  /* Set the request Content-Type header to 'application/json' to process the request as JSON. */
  request.setRequestHeader('Content-Type', 'application/json');

  /* Finally send the request. */
  request.send(JSON.stringify(event));

};
</code>
<br>
<h5>2: The report function can now be called with an argument which will then be passed on in the request to tedmetrics. You can now call this function to help you track events such as click events:</h5>

<code>&lt;a href="/about" onclick="tedmetrics.report('about link clicked')"&gt;
</code>

<h5>or even execute when a page is loaded:</h5>
<code>&lt;script&gt;tedmetrics.report('about page loaded');&lt;/script&gt;
</code>
<br>

<h5>That's it! You're ready to go. Make sure to register your app on tedmetrics and start tracking your data here.</h5>

app/views/welcome/landing.html.erb
<div id="app_title">
  <h1 class="headers">Welcome to tedmetrics</h1>
  <h5 class="center">An analytics tool for you. Create an account to track activity on your applications: </h5>
  <div class="center home-btns">
    <%= link_to "Sign Up", new_user_registration_path, :class => 'waves-effect waves-light btn'  %>
    <%= link_to "Sign In", new_user_session_path, :class => 'waves-effect waves-light btn'  %>
  </div>
</div>